import React from "react";
import $ from 'jquery';

setInterval(dis, 1000);

//Start is used to determine when the Start button is pressed (1/0)
let start = sessionStorage.getItem("start");

//The score of the game
let score = 0;

//rep is a set of random numbers from 0 to 11
let rep = [];

//counter is used to check if the game has completed the steps (i.e 12 steps)
let counter = 0;

//rep is then set to a list of random numbers from 0 to 11
rep = Myrand();

//kk is the 15 seconds to wait for text to display
let kk = 15;

//Generates a list of 0-11 and calls the shuffle function (Pass By Reference)
function Myrand() {
    var ranNums = shuffle([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);
    return ranNums;
}

//The passed list/array is then shuffled and returned to ranNums
function* shuffle(array) {
    var i = array.length;
    while (i--) {
        yield array.splice(Math.floor(Math.random() * (i + 1)), 1)[0];
    }
}


//dis function is the main function of this program, it is called per second and condition is checked if to on the timer or not
function dis() {
    //start is initialized with the session 'start' per second
    start = sessionStorage.getItem("start");

    //If start turns to 1 then the following code is executed
    if (parseInt(start) === 1) {
        //The timer is on and kk is decremented by 1
        document.getElementById("time").innerText = kk + " sec";
        kk--;

        //When the counter is smaller than 12 and kk is -1 i.e 0 then the below code is executed
        if (parseInt(counter) < 12 && kk === -1) {
            //kk is again set to 15
            kk = 15;

            //The user clicked input is taken from the table
            let t1 = sessionStorage.getItem("t1");

            //The user input is resetted to 0 
            sessionStorage.setItem("t1", 0);

            //The number generated by the host is being generated
            const sa = JSON.parse(sessionStorage.getItem("items"));
            let rand = rep.next().value;

            //num is set to the random number (it acts as the host)
            let num = sa[rand];
            
            //The counter is incemented by 1
            counter ++;

            //The host number is displayed
            document.getElementById("result").innerText = "Number is " + num;

            //If the host number(num) matched the user input from table (t1) the execute below code
            if (parseInt(num) === parseInt(t1)) {
                //Set the color of the <td> table to green and font color to white
                document.getElementById(t1).style.backgroundColor = "green";
                document.getElementById(t1).style.color = "white";

                //Score is incremented by 10
                score += 10;
                
                //The incremented score is then stored in the session
                sessionStorage.setItem("score", score);

                //The score is displayed on the screen
                document.getElementById("score").innerText = "Score : " + score;


                //The +10 animation is played at the side of the score
                document.getElementById("")
                $('<span class="plus-one"/>', {
                    style: 'display:none'
                })
                    .html('+10')
                    .appendTo($('.add-comment'))
                    .fadeIn('1000', function () {
                        var el = $(this);
                        setTimeout(function () {
                            el.remove();
                        }, 2000);
                    });
            }
            //If the hosts number(num) does not match the player input table(t1)
            else {
                document.getElementById(num).style.backgroundColor = "red";
                document.getElementById(num).style.color = "white";
            }
        }
        //When the value of counter passes 11 then execute the below code 
        else if (parseInt(counter) > 11) {
            //The start value is set to 0 which will stop the timer and the host number generation
            sessionStorage.setItem("start", 0);
            document.getElementById("result").innerText = "Game is Over!";
        }
    }

}

export default function Number() {

    return (
        <div >
            <h1 id="result">Number</h1>
        </div>
    )
}
